### ISSUE TITLE
About how to set to Chinese display

### ISSUE THREAD

**Issue by Hfy-xxx** [ComfyFactory/ComfyFactorio#188]
I am not clear about how to set Chinese in the issues, can you tell me how to set the locale in the scene map to Chinese?

**Comment by Gerkiz** [comment]
Hello,
Any particular maps you have in mind?

**Comment by itamzxm** [comment]
小兄弟。都是会自动匹配语言的，如果没有中文，就是没有翻译。你可以看我的github。https://github.com/itamzxm/ComfyFactorio-Chinese-Translation-
这里的是中文版本的

**Comment by hanakocz** [comment]
#181 was merged, so if map has chinese translation, it now will work automatically for the maps that were translated, you just need to play the game in chinese.
