### ISSUE TITLE
I would like to learn how to make gameplay maps. Where can I find a documented tutorial?

### ISSUE THREAD

**Issue by cyan-river** [ComfyFactory/ComfyFactorio#233]
I would like to learn how to make gameplay maps. Where can I find a documented tutorial?

**Comment by Gerkiz** [comment]
I'd suggest reading here:
https://wiki.factorio.com/Scenario_system

There are various posts:
https://forums.factorio.com/viewtopic.php?t=2070

Also the API is worth to read:
https://lua-api.factorio.com/latest/
