### ISSUE TITLE
MTN: Coin dropped at worm location when killed by Rocket launcher

### ISSUE THREAD

**Issue by vadcx** [ComfyFactory/ComfyFactorio#453]
It's the first time I've seen this. I'm not sure this can be fixed easily or going as far as tracking who was the last player damaging the entity?

I was killing worms with RPG and the coin spawned on the worm, across the ravine, so I couldn't get it.

![coinworm](https://github.com/ComfyFactory/ComfyFactorio/assets/129969897/f1e649d1-146c-4ffc-b1ec-d2665a1eb8c1)

**Comment by Gerkiz** [comment]
I don't really see this as an issue as you can utilize explosives to landfill and reach your coins.
I'll probably not do anything to this as of now.
