### ISSUE TITLE
MTN: Spawning wrecks during mining can get the player stuck

### ISSUE THREAD

**Issue by vadcx** [ComfyFactory/ComfyFactorio#454]
I had no ammo on me and couldn't break myself free. You can't break them with bare hands. This thing spawned on me while I was mining rocks. I think the player should be moved out if were to become stuck.

Whether to apply the same to biters is debatable. They can get you stuck inside them the same way.

![stuckmining](https://github.com/ComfyFactory/ComfyFactorio/assets/129969897/8b6903c3-17c3-4e4f-82fc-4db4fbb7d140)

**Comment by Gerkiz** [comment]
I've adjusted the function `Public.unstuck_player` so it's called 5 ticks after the entity spawn, thus it should allow the function to get a better result.
