### ISSUE TITLE
MTN: Spawned loot chest inside another building (unreachable)

### ISSUE THREAD

**Issue by vadcx** [ComfyFactory/ComfyFactorio#455]
This chest was dropped from one of the trees I mined. I don't know which came first, tree underneath the outpost or outpost spawned under the tree. Either way, I think the chest should've been spawned outside to be reachable by hand.

In this particular situation, it would've been possible to extract the items using an inserter. But I don't consider this normal.

![unreachablechest](https://github.com/ComfyFactory/ComfyFactorio/assets/129969897/91622c36-0bf5-4391-8210-b1c64527c5bc)

**Comment by Gerkiz** [comment]
This should now be fixed in the next release. The function now checks specifically for a market before spawning the chest, if a market is found then it'll utilize `find_non_colliding_position` before spawning the chest in the new position.
