### ISSUE TITLE
MTN: Pushback at highest allowed depth (zone limit) can stuck player

### ISSUE THREAD

**Issue by vadcx** [ComfyFactory/ComfyFactorio#456]
When the train is too far behind, players are disallowed from continuing north. This is done by teleporting the player back south with a warning message to the player. However (especially with high movement speeds) it is possible the player will be teleported next to a void tile and get stuck.

This happened twice on the same spot yesterday... and somehow I don't have the screenshot anymore. It looked kinda like this:

`X` is pathable tile. `O` is void. Where `---` is the first disallowed tile by height. 

```
   XXXXX
   XXXOO
---XXOOO---
   XXxOO
```

_Trying to recall what happened:_ The first player was teleported to small `x` and called for help. Then when I came running at full speed, I went past the line diagonally (going top-right) and got teleported to the same spot and so we got stuck together while being attacked by worms.

We barely managed to escape by exploding a chest and generating another earth tile to move on.

----

Similarly a little earlier I got stuck-teleported behind the unmine-able zone border wall. It was not as bad but still annoying:

`L` is border wall (can only be destroyed by shooting) and `W` is water. Factorio desided to teleport me BETWEEN the border wall and water. Thus I was unable to move left or right and could only shoot myself free.

```
---XXXXX---
   XXXXX
   LLLLL
   WWWWW
```

**Comment by Gerkiz** [comment]
This will be fixed in the next release. Thank you posting this issue!
