### ISSUE TITLE
RPG Magic: Changing skill in settings menu doesn't deselect previous skill

### ISSUE THREAD

**Issue by vadcx** [ComfyFactory/ComfyFactorio#457]
I play on Mountain fortress, based on my experience there

Reproduction:

1. Choose all 3 skills in menu, save
2. Select any skill. Let's say slot 2
3. Go to settings, change slot 2. Save
4. Try to cast slot 2 without clicking it again.

Actual: The previous skill will be cast (before the latest choice change)

Expected: Newly selected skill to be cast.

Workaround: Select another skill and then skill 2 to refresh the setting.

**Comment by Gerkiz** [comment]
This will be fixed in the next release. 

https://github.com/ComfyFactory/ComfyFactorio/assets/39602942/78f95ccb-ab05-4102-9cc3-f8173e4c3b06
